# Generated by Django 2.0.2 on 2019-01-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contingent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namec', models.CharField(max_length=30)),
                ('phonec', models.CharField(max_length=10)),
                ('collegec', models.CharField(max_length=200)),
                ('emailc', models.CharField(max_length=200)),
                ('numberc', models.IntegerField()),
            ],
        ),
    ]
