# Generated by Django 2.0.2 on 2019-01-17 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contingent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contingent',
            old_name='collegec',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='contingent',
            old_name='emailc',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contingent',
            old_name='namec',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contingent',
            old_name='numberc',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='contingent',
            old_name='phonec',
            new_name='phone',
        ),
    ]
