# Generated by Django 2.0.2 on 2019-01-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contingent', '0003_contingent_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contingent',
            old_name='college',
            new_name='contingent',
        ),
        migrations.RemoveField(
            model_name='contingent',
            name='number',
        ),
    ]
