# Generated by Django 2.0.2 on 2019-01-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
