# Generated by Django 2.0.2 on 2019-01-19 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_pdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='pdate',
            new_name='date',
        ),
    ]
